[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#d9b99b'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#87ceeb'

# Color used for almost all text
textColor = '#4f4439'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"